sudo: required
services:
  - docker

before_install:
  - docker build -t forceedge01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true forceedge01/react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t forceedge01/multi-client ./client
  - docker build -t forceedge01/multi-nginx ./nginx
  - docker build -t forceedge01/multi-server ./server
  - docker build -t forceedge01/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push forceedge01/multi-client
  - docker push forceedge01/multi-nginx
  - docker push forceedge01/multi-server
  - docker push forceedge01/multi-worker
